"use client";

// =======================================================================

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// =======================================================================

import Navbar from "./modules/navbar/navbar.jsx";
import Footer from "./modules/footer/footer.jsx";
import { usePathname } from "next/navigation";

// =======================================================================

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  // =======================================================================

  const pathname = usePathname();

  // Define the pages where you want to hide the NavBar
  const hideNavBarPages = [""];

  const shouldShowNavBar = !hideNavBarPages.includes(pathname);

  // =======================================================================

  return (
    <>
      <html lang="en">
        {/* ------------------------------------- */}
        <head>
          <link rel="icon" href="/favicon.ico" />
          <title>SE6A - Attendance Portal</title>
        </head>
        {/* ------------------------------------- */}
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* ================================================= */}
          {shouldShowNavBar && <Navbar />}
          {/* ================================================= */}
          {children}
          {/* ================================================= */}
          {shouldShowNavBar && <Footer />}
          {/* ================================================= */}
        </body>
      </html>
    </>
  );
}
